# Generated by Django 3.1.5 on 2022-12-18 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
